### PR TITLE
Assignment 3

### PR DESCRIPTION
**Pull request by ancakurian**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Upload dataset, write code for statistical analysis, and visualization; compare features.

## What did you learn from the changes you have made?
I did learn that data analysis is influenced by the statistical tools used. It is important to understand the data and not to overread into it.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
In bootstrapping, I could have not calculated the sample mean value, but I did decide to include it because it is almost identical with the mean of the values include in the confidence interval.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Writing code and correcting my own work, but nothing unexpected.

## How were these changes tested?
Each code was run as written.

## A reference to a related issue in your repository (if applicable)
No.

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by HongleiXie** [comment]
You have unfortunately made a pull request to the wrong repo. You shouldn't be making a pull request to UofT-DSI/applying_statistical_concepts, but rather your own forked applying_statistical_concepts repo. Please read the instructions on your onboarding [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md) more carefully.

**Comment by ancakurian** [comment]
Hello Holly,

Thank you for your feedback.

I've noticed my mistake as soon as I made the pull request and I created a
new one right away from my one repository. I do see it on my end.
What should I do now, do I create another one or the one I have done is
valid (I attached the screenshot of the page)?

Thank you,
Anca Kurian

**Comment by ancakurian** [comment]
Hello Holly,

I read the comment that you wrote on my assignment 3 (closed #128).
However, Assignment 3 had already been marked complete on Oct 18.

It was Assignment 2 that I resubmitted on Oct 18 and created a pull request
from the UofT DSI repo. I did a second pull request from my fork and
submitted almost immediately as I noticed my mistake. It is Assignment 2
that shows unmarked on my repo.

Could you please clarify if there is anything else I should be doing or if
all three assignments are accepted?

Thank you,

Anca Kurian

**Comment by HongleiXie** [comment]
Rest assured your assignments have been submitted.

**Pull request closed without merging**
